/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lintr;
import java.io.File;
import java.util.Scanner;
import java.io.FileNotFoundException;
import java.util.HashMap;


public class App {

    public static void main(String[] args) {
        App a = new App();
        String filePath = "src/main/resources/gates.js";
        a.findLintrErrors(filePath);
    }


    public int findLintrErrors(String filePath) {
        int errorCount = 0;
        try {
            Scanner sc = new Scanner(new File(filePath));
            int lineCount = 0;

            while (sc.hasNextLine()) {
                lineCount++;
                String line = sc.nextLine();

                    if(!(line.isEmpty()) && (!line.endsWith("{") ) && (!line.endsWith("}")) && (!line.contains("if")) && (!line.contains(("else")) && (!line.endsWith(";")))) {
                                System.out.println("Error found on line " + lineCount + " missing semicolon.");
                                errorCount++;
                    }
            }

        } catch (FileNotFoundException e) {
            System.out.println("File not found");
            System.out.println(e);
            return errorCount;
        }
        System.out.println("The number of errors found were: " + errorCount);
        return errorCount;
    }
}