/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant extends Business {

    private int rating;
    private String price;

    public Restaurant(String name, int rating, String price) {
       super(name);
       this.rating = rating;
       this.price = price;
    }

    public String toString(){
        return String.format("%s has a rating of %d and is priced at %s. The following are the review from ont of our customers %s: %s", this.getName(), this.getTotalRating(), this.price, reviewsFromCustomers.get(1).getAuthor(), reviewsFromCustomers.get(1).getBody());

    }

}

