/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant {

    private String name;
    private int rating;
    private String price;

    public Restaurant() {};
    public Restaurant(String name, int rating, String price) {
        this.name = name;
        this.rating = rating;
        this.price = price;
    }

    public String toString(){
        return String.format("%s has a rating of %d and is priced at %s", this.name, this.rating, this.price);
    }

    public void addReview(){
        

    }

}



