/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test
    public void testConstructor() {
        Restaurant classUnderTest = new Restaurant();
        Restaurant subway = new Restaurant("Subway", 3, "$$");
        assertEquals("Subway has a rating of 3 and is priced at $$", subway.toString());
    }
}
