/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


public class Library {
    public int[] roll(int n) {
        int[] rolledArray = new int [n];
        for (int i=0; i<n; i++) {
            int rolledNumber = (int) ((Math.random() * 6)+1);
            rolledArray[i]=rolledNumber;
        }
        return rolledArray;
    }

    public boolean containsDuplicates(int[] arrayToTestForDuplicates){
        for (int i = 0; i<arrayToTestForDuplicates.length; i++){
            for (int j = i+1; j<arrayToTestForDuplicates.length; j++){
                if((arrayToTestForDuplicates[i])==(arrayToTestForDuplicates[j])){
                    return true;
                }
            }
        }
        return false;
    }

    public double calculatingAverages(double[] arrayForAverage){
        double total = 0;
        for(double numbers : arrayForAverage){
            total += numbers;
        }
        return total/(arrayForAverage.length);
    }

    public int[] arrayWithLowestAverage(int[][] arrayOfArrays) {
        int lowestTotal=0;
        int indexOfLowest = 0;
        for (int i = 0; i<arrayOfArrays.length; i++){
            int total = 0;
            for(int j = 0; j<arrayOfArrays[i].length; j++){
                total+=arrayOfArrays[i][j];
            }
            if(i == 0) {
                lowestTotal = total;
            }
            else if (total<=lowestTotal){
                lowestTotal = total;
                indexOfLowest = i;
            }
        }
        return arrayOfArrays[indexOfLowest];
    }

}
